# # see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
outgoing:
  request_timeout: 5.0       # default timeout in seconds, can be override by engine
  max_request_timeout: 200.0  # the maximum timeout in seconds
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "megasecretkey"  # change this!
  limiter: false  # can be disabled for a private instance
  image_proxy: true
search:
  method: GET
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
enabled_plugins:
  - 'Hostnames plugin'
hostnames:
  replace:
    '(.*\.)?youtube\.com$':           'invidious.privacyredirect.com'
    '(.*\.)?youtu\.be$':              'invidious.privacyredirect.com'
    '(.*\.)?youtube-noocookie\.com$': 'invidious.privacyredirect.com'
  remove:
    - '(.*\.)?reddit\.com$'
    - '(.*\.)?redd\.it$'
    - '(.*\.)?twitter\.com$'
    - '(.*\.)?medium\.com$'
    - '(.*\.)?geeksforgeeks\.org$'
    - '(.*\.)?w3schools\.com$'
    - '(.*\.)?datacamp\.com$'
    - '(.*\.)?towardsdatascience\.com$'
