# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "megasecretkey"  # change this!
  limiter: true  # can be disabled for a private instance
  image_proxy: true
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
enabled_plugins:
  - 'Hostname replace'
hostname_replace:
  '(.*\.)?youtube\.com$':           invidious.privacyredirect.com
  '(.*\.)?youtu\.be$':              invidious.privacyredirect.com
  '(.*\.)?youtube-noocookie\.com$': invidious.privacyredirect.com
  '(.*\.)?reddit\.com$':            false
  '(.*\.)?redd\.it$':               false
  '(www\.)?twitter\.com$':          false
  'www\.libhunt\.com':              false
  '(www\.)?medium\.com$': false
  '(www\.)?geeksforgeeks\.org$': false
  '(www\.)?w3schools\.com$': false
  '(www\.)?datacamp\.com$': false
  '(www\.)?towardsdatascience\.com$': false