-- Macaulay2 script for computing Gröbner bases

-- Create a polynomial ring over the rationals with variables x, y, z
R = QQ[x,y,z]

-- Define an ideal generated by some polynomials
I = ideal(x^2 + y^2 - 1, x*y - z^2)

-- Compute the Gröbner basis
G = gens gb I

-- Display the result
print("Original ideal generators:")
print gens I
print("Gröbner basis:")
print G

-- Verify it's the same ideal
print("Verification - ideal equality:")
print(I == ideal G)

-- Show some properties
print("Dimension of the variety:")
print dim I
print("Degree:")  
print degree I
