#!/bin/bash
# BASELINE SMOKE TEST — DO NOT EDIT THIS FILE. IT MUST WORK.
# Verifies the core jupyter-dape flow: connect, breakpoint, next, continue.
# This was confirmed working before any session-restart changes.

DAEMON=jdape-baseline
EC="emacsclient -s $DAEMON"
JUPYTER_DAPE=/home/zjabbar/code/guix-channel/zaijab/files/jupyter-dape.el
TEST_PY=/home/zjabbar/code/guix-channel/zaijab/files/test.py

emacsclient -s $DAEMON -e '(kill-emacs)' 2>/dev/null || true
sleep 0.5

emacs -q --daemon=$DAEMON 2>&1
trap "$EC -e '(kill-emacs)' 2>/dev/null || true" EXIT

$EC -e "(progn (require 'package) (package-initialize) (require 'dape) (require 'jupyter) (load-file \"$JUPYTER_DAPE\") (jupyter-dape-mode 1) (find-file \"$TEST_PY\") t)" 2>/dev/null

$EC -e '(jupyter-run-repl "python3")' > /dev/null 2>&1
echo "Waiting for kernel..."
sleep 5

$EC -e "(let* ((rb (cl-find-if (lambda (b) (string-match-p \"jupyter-repl\" (buffer-name b))) (buffer-list))) (c (and rb (with-current-buffer rb jupyter-current-client)))) (when c (with-current-buffer \"test.py\" (jupyter-repl-associate-buffer c))) t)" 2>/dev/null

$EC -e "(with-current-buffer \"test.py\" (goto-char (point-min)) (forward-line 9) (dape-breakpoint-toggle) t)" 2>/dev/null

$EC -e "(with-current-buffer \"test.py\" (dape (dape--config-eval 'jupyter-dape (cdr (assoc 'jupyter-dape dape-configs)))))" > /dev/null 2>&1
echo "Waiting for dape..."
sleep 5

echo "Connections: $($EC -e '(length (dape--live-connections))' 2>&1)"

$EC -e "(with-current-buffer \"test.py\" (jupyter-eval-string (buffer-substring-no-properties (point-min) (point-max))))" > /dev/null 2>&1
echo "Waiting for breakpoint..."
sleep 5

STOPPED=$($EC -e '(not (null (dape--stopped-threads (car (dape--live-connections)))))' 2>&1)
echo "Breakpoint hit: $STOPPED"

$EC -e '(dape-next (car (dape--live-connections)))' > /dev/null 2>&1
sleep 2
echo "After next — connections: $($EC -e '(length (dape--live-connections))' 2>&1)"

if [ "$STOPPED" = "t" ]; then
    echo "BASELINE PASS"
else
    echo "BASELINE FAIL"
    exit 1
fi
